version: "3.8"
services:
  mongo:
    image: mongo:6.0.5
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=url_shortener
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
      - ./configs/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  redis:
    image: redis:7.0-alpine3.18
    restart: always
    ports:
      - "6379:6379"
  zoo:
    image: zookeeper:3.8.1
    restart: always
    ports:
      - "2181:2181"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - zoo
    links:
      - mongo
      - redis
      - zoo
volumes:
  mongo-data:

#  mongosh --username aryahmph --password aryahmph --authenticationDatabase url_shortener